function [fitresult, gof] = createFit1(x, y, a, b)
%CREATEFIT1(ALL_X)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : all_x
%      Y Output: all_x
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Jan-2022 10:56:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Lower = [b a];
opts.Upper = [b a];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


